local dpi   = require("beautiful.xresources").apply_dpi

local theme                                     = {}
theme.accent     				= "#79838D"
theme.dir                                       = os.getenv("HOME") .. "/.config/awesome/themes/rpg"
theme.wallpaper                                 = os.getenv("HOME") .. "/.config/awesome/wallpaper.jpg"
theme.font                                      = "Terminus 12"
theme.taglist_font                              = "Hack Nerd Font Mono 12"
theme.icon_font 				= "Hack Nerd Font Mono 12"
theme.icon_accent 				= theme.accent
theme.fg_normal                                 = "#ffffff"
theme.fg_focus                                  = "#ffffff"
theme.fg_urgent                                 = "#CC9393"
theme.bg_normal                                 = "#121212"
theme.bg_focus                                  = theme.accent
theme.bg_urgent                                 = "#2A1F1E"
theme.border_width                              = dpi(2)
theme.border_normal                             = "#00000000"
theme.border_focus                              = theme.accent
theme.titlebar_bg_normal                        = "#121212"
theme.titlebar_fg_normal                        = "#ffffff"
theme.titlebar_bg_focus                         = "#292929"
theme.titlebar_fg_focus                         = "#ffffff"
theme.notification_bg                           = theme.accent
theme.notification_fg                           = "#ffffff"
theme.notification_border_color                 = theme.accent
theme.notification_border_width                 = dpi(2)
theme.notification_width                        = dpi(325)
theme.taglist_fg_focus                          = theme.accent
theme.taglist_fg_occupied 			= "#6C7885" 
theme.taglist_bg_focus                          = "#00000000"
theme.taglist_bg_occupied 			= "#00000000"
theme.taglist_spacing 				= dpi(0)
-- theme.taglist_squares_sel                       = theme.dir .. "/icons/square_sel.png"
-- theme.taglist_squares_unsel                     = theme.dir .. "/icons/square_unsel.png"
theme.bar_height                                = dpi(32)
theme.menu_height                               = dpi(24)
theme.menu_width                                = dpi(96)
theme.menu_submenu_icon                         = theme.dir .. "/icons/submenu.png"
theme.awesome_icon                              = theme.dir .. "/icons/awesome.png"
theme.layout_tile                               = theme.dir .. "/icons/tile/tile.png"
theme.layout_tileleft                           = theme.dir .. "/icons/tile/tileleft.png"
theme.layout_tilebottom                         = theme.dir .. "/icons/tile/tilebottom.png"
theme.layout_tiletop                            = theme.dir .. "/icons/tile/tiletop.png"
theme.layout_fairv                              = theme.dir .. "/icons/tile/fairv.png"
theme.layout_fairh                              = theme.dir .. "/icons/tile/fairh.png"
theme.layout_spiral                             = theme.dir .. "/icons/tile/spiral.png"
theme.layout_dwindle                            = theme.dir .. "/icons/tile/dwindle.png"
theme.layout_max                                = theme.dir .. "/icons/tile/max.png"
theme.layout_fullscreen                         = theme.dir .. "/icons/tile/fullscreen.png"
theme.layout_magnifier                          = theme.dir .. "/icons/tile/magnifier.png"
theme.layout_floating                           = theme.dir .. "/icons/tile/floating.png"
theme.useless_gap                               = dpi(3)
theme.gap_single_client                         = true
theme.systray_icon_spacing                      = dpi(1)
theme.systray_size 				= dpi(12)
theme.widget_spacing 				= dpi(12)
theme.tasklist_plain_task_name                  = false
theme.tasklist_disable_task_name                = false
theme.titlebar_close_button_focus               = theme.dir .. "/icons/titlebar/close_focus.png"
theme.titlebar_close_button_normal              = theme.dir .. "/icons/titlebar/close_normal.png"
theme.titlebar_ontop_button_focus_active        = theme.dir .. "/icons/titlebar/ontop_focus_active.png"
theme.titlebar_ontop_button_normal_active       = theme.dir .. "/icons/titlebar/ontop_normal_active.png"
theme.titlebar_ontop_button_focus_inactive      = theme.dir .. "/icons/titlebar/ontop_focus_inactive.png"
theme.titlebar_ontop_button_normal_inactive     = theme.dir .. "/icons/titlebar/ontop_normal_inactive.png"
theme.titlebar_sticky_button_focus_active       = theme.dir .. "/icons/titlebar/sticky_focus_active.png"
theme.titlebar_sticky_button_normal_active      = theme.dir .. "/icons/titlebar/sticky_normal_active.png"
theme.titlebar_sticky_button_focus_inactive     = theme.dir .. "/icons/titlebar/sticky_focus_inactive.png"
theme.titlebar_sticky_button_normal_inactive    = theme.dir .. "/icons/titlebar/sticky_normal_inactive.png"
theme.titlebar_floating_button_focus_active     = theme.dir .. "/icons/titlebar/floating_focus_active.png"
theme.titlebar_floating_button_normal_active    = theme.dir .. "/icons/titlebar/floating_normal_active.png"
theme.titlebar_floating_button_focus_inactive   = theme.dir .. "/icons/titlebar/floating_focus_inactive.png"
theme.titlebar_floating_button_normal_inactive  = theme.dir .. "/icons/titlebar/floating_normal_inactive.png"
theme.titlebar_minimize_button_focus_active    = theme.dir .. "/icons/titlebar/minimized_focus_active.png"
theme.titlebar_minimize_button_normal_active   = theme.dir .. "/icons/titlebar/minimized_normal_active.png"
theme.titlebar_minimize_button_focus_inactive  = theme.dir .. "/icons/titlebar/minimized_focus_inactive.png"
theme.titlebar_minimize_button_normal_inactive = theme.dir .. "/icons/titlebar/minimized_normal_inactive.png"
theme.titlebar_maximized_button_focus_active    = theme.dir .. "/icons/titlebar/maximized_focus_active.png"
theme.titlebar_maximized_button_normal_active   = theme.dir .. "/icons/titlebar/maximized_normal_active.png"
theme.titlebar_maximized_button_focus_inactive  = theme.dir .. "/icons/titlebar/maximized_focus_inactive.png"
theme.titlebar_maximized_button_normal_inactive = theme.dir .. "/icons/titlebar/maximized_normal_inactive.png"

theme.cpu_icon 					= ""
theme.gpu_icon 					= "理"
theme.ram_icon 					= ""
theme.vol_icon 					= "墳"
theme.cal_icon 					= ""
theme.clock_icon 				= ""
theme.vpn_icon_connected 			= "聯"
theme.vpn_icon_disconnected 			= "輦"
theme.music_icon 				= ""
theme.taglist_icons 				= {"","","",""}

return theme
