local dpi   = require("beautiful.xresources").apply_dpi
local pywal = require("awesomewm-colors")


local theme                                     = {}
theme.accent     				= pywal.color3
theme.dir                                       = os.getenv("HOME") .. "/.config/awesome/themes/variety"
theme.wallpaper                                 = os.getenv("HOME") .. "/.config/awesome/wallpaper.jpg"
theme.font                                      = "Intern 12"
theme.taglist_font                              = "Font Awesome 5 Free 10"
theme.icon_font 				= "Font Awesome 5 Free 12"
theme.icon_accent 				= theme.accent
theme.fg_normal                                 = "#ffffff"
theme.fg_focus                                  = "#ffffff"
theme.fg_urgent                                 = "#CC9393"
theme.bg_normal                                 = "#121212"
theme.bg_focus                                  = theme.accent
theme.bg_urgent                                 = "#2A1F1E"
theme.border_width                              = dpi(2)
theme.border_normal                             = "#00000000"
theme.border_focus                              = theme.accent
theme.titlebar_bg_normal                        = "#121212"
theme.titlebar_fg_normal                        = "#ffffff"
theme.titlebar_bg_focus                         = "#292929"
theme.titlebar_fg_focus                         = "#ffffff"
theme.notification_bg                           = "#121212"
theme.notification_fg                           = "#ffffff"
theme.notification_border_color                 = theme.accent
theme.notification_border_width                 = dpi(3)
theme.notification_width                        = dpi(375)
theme.taglist_fg_focus                          = "#ffffff"
theme.taglist_bg_focus                          = theme.accent
theme.taglist_bg_occupied 			= pywal.color2
theme.taglist_spacing 				= dpi(0)
-- theme.taglist_squares_sel                       = theme.dir .. "/icons/square_sel.png"
-- theme.taglist_squares_unsel                     = theme.dir .. "/icons/square_unsel.png"
theme.bar_height                                = dpi(27)
theme.menu_height                               = dpi(25)
theme.menu_width                                = dpi(150)
theme.menu_submenu_icon                         = theme.dir .. "/icons/submenu.png"
theme.awesome_icon                              = theme.dir .. "/icons/awesome.png"
theme.layout_tile                               = theme.dir .. "/icons/tile_c_1.png"
theme.layout_tileleft                           = theme.dir .. "/icons/tileleft.png"
theme.layout_tilebottom                         = theme.dir .. "/icons/tilebottom.png"
theme.layout_tiletop                            = theme.dir .. "/icons/tiletop.png"
theme.layout_fairv                              = theme.dir .. "/icons/fairv.png"
theme.layout_fairh                              = theme.dir .. "/icons/fairh.png"
theme.layout_spiral                             = theme.dir .. "/icons/spiral.png"
theme.layout_dwindle                            = theme.dir .. "/icons/dwindle.png"
theme.layout_max                                = theme.dir .. "/icons/max.png"
theme.layout_fullscreen                         = theme.dir .. "/icons/fullscreen.png"
theme.layout_magnifier                          = theme.dir .. "/icons/magnifier.png"
theme.layout_floating                           = theme.dir .. "/icons/floating_c_1.png"
theme.useless_gap                               = dpi(3)
theme.gap_single_client                         = false
theme.systray_icon_spacing                      = dpi(1)
theme.tasklist_plain_task_name                  = false
theme.tasklist_disable_task_name                = false
theme.titlebar_close_button_focus               = theme.dir .. "/icons/titlebar/close_focus.png"
theme.titlebar_close_button_normal              = theme.dir .. "/icons/titlebar/close_normal.png"
theme.titlebar_ontop_button_focus_active        = theme.dir .. "/icons/titlebar/ontop_focus_active.png"
theme.titlebar_ontop_button_normal_active       = theme.dir .. "/icons/titlebar/ontop_normal_active.png"
theme.titlebar_ontop_button_focus_inactive      = theme.dir .. "/icons/titlebar/ontop_focus_inactive.png"
theme.titlebar_ontop_button_normal_inactive     = theme.dir .. "/icons/titlebar/ontop_normal_inactive.png"
theme.titlebar_sticky_button_focus_active       = theme.dir .. "/icons/titlebar/sticky_focus_active.png"
theme.titlebar_sticky_button_normal_active      = theme.dir .. "/icons/titlebar/sticky_normal_active.png"
theme.titlebar_sticky_button_focus_inactive     = theme.dir .. "/icons/titlebar/sticky_focus_inactive.png"
theme.titlebar_sticky_button_normal_inactive    = theme.dir .. "/icons/titlebar/sticky_normal_inactive.png"
theme.titlebar_floating_button_focus_active     = theme.dir .. "/icons/titlebar/floating_focus_active.png"
theme.titlebar_floating_button_normal_active    = theme.dir .. "/icons/titlebar/floating_normal_active.png"
theme.titlebar_floating_button_focus_inactive   = theme.dir .. "/icons/titlebar/floating_focus_inactive.png"
theme.titlebar_floating_button_normal_inactive  = theme.dir .. "/icons/titlebar/floating_normal_inactive.png"
theme.titlebar_minimize_button_focus_active    = theme.dir .. "/icons/titlebar/minimized_focus_active.png"
theme.titlebar_minimize_button_normal_active   = theme.dir .. "/icons/titlebar/minimized_normal_active.png"
theme.titlebar_minimize_button_focus_inactive  = theme.dir .. "/icons/titlebar/minimized_focus_inactive.png"
theme.titlebar_minimize_button_normal_inactive = theme.dir .. "/icons/titlebar/minimized_normal_inactive.png"
theme.titlebar_maximized_button_focus_active    = theme.dir .. "/icons/titlebar/maximized_focus_active.png"
theme.titlebar_maximized_button_normal_active   = theme.dir .. "/icons/titlebar/maximized_normal_active.png"
theme.titlebar_maximized_button_focus_inactive  = theme.dir .. "/icons/titlebar/maximized_focus_inactive.png"
theme.titlebar_maximized_button_normal_inactive = theme.dir .. "/icons/titlebar/maximized_normal_inactive.png"

return theme
