format = """
(bold fg:5)  $all (bold fg:2)><> """
#Add a blank line BEFORE the prompt
add_newline = false 

#Add a blank link between prompt and input
[line_break]
disabled = false

[character]
success_symbol = "[»](bold fg:2)"
error_symbol = "[✖](bold fg:5) "
disabled = true

[directory]
truncation_length = 3
style = "bold fg:3"
read_only =""
truncation_symbol = "../"

[nodejs]
symbol = "NodeJS "

