#! /bin/sh
#get colors from .Xresources
getcolors () {
	FG=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
	BG=$(xrdb -query | grep 'background:'| awk '{print $NF}')
	COLOR0=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
	COLOR1=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
	COLOR2=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
	COLOR3=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
	COLOR4=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
	COLOR5=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
	COLOR6=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
	COLOR7=$(xrdb -query | grep 'color7:'| awk '{print $NF}')
}
getcolors

#fix cursors
xsetroot -cursor_name left_ptr

#start some daemons and apps
## restart window titles daemon
echo "" > ~/.cache/bspwm_windows_1
echo "" > ~/.cache/bspwm_windows_2
while pgrep -u $UID -f ~/.config/bspwm/bspwm_window_titles.sh >/dev/null; do pkill -f ~/.config/bspwm/bspwm_window_titles.sh; done
~/.config/bspwm/bspwm_window_titles.sh &

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x feh > /dev/null || sh ~/.fehbg
~/.config/polybar/launch.sh
~/.config/bspwm/autostart.sh

#bspwm settings
bspc monitor DP-4 -d 1 2 3 4
bspc monitor DP-2 -d 1 2 3 4

bspc config focused_border_color "$COLOR4" 
bspc config normal_border_color "$BG"
bspc config active_border_color "$COLOR4"
bspc config presel_feedback_color "$COLOR4"

bspc config border_width 3
bspc config window_gap 12

bspc config split_ratio 0.50
bspc config automatic_scheme alternate

bspc config pointer_follows_monitor true
bspc config focus_follows_pointer true

bspc rule -a firefox desktop='^1' follow=on
bspc rule -a Steam desktop='^2' state=tiled follow=on
bspc rule -a Steam:\*:'Friends List' monitor='^2'
bspc rule -a Lutris desktop='^2' state=tiled follow=on
bspc rule -a kitty desktop='^3' state=tiled follow=on
bspc rule -a Origin state=floating
bspc rule -a \* center=on

bsp-layout set tall 1 --master-size 0.5
bsp-layout set tall 2 --master-size 0.5
bsp-layout set tall 3 --master-size 0.5
bsp-layout set tall 4 --master-size 0.5
