#!/usr/bin/env bash

#load colors generated by pywal
source /home/lenan/.cache/wal/colors.sh

function run {
    if ! pgrep -f $1 ;
    then
        $@&
    fi   
}

#
# mouse gets set to second monitor by default...
# use this to move mouse to center of first monitor
#
xdotool mousemove 1280 720

#
# autostart programs
#
run unclutter --root
run /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
#run /usr/lib/polkit-kde-authentication-agent-1
# start-pulseaudio-x11
#run qjackctl
#run cadence-session-start --system-start
#run nvidia-settings --load-config-only
run picom --experimental-backends &
run numlockx on &
# run caffeine-ng
sleep 1
#run blueman-applet &
#run keepassxc
#run variety
run syncthingtray-qt6
run redshift-qt -l 41.722058311352065:2.9302747751915774 -t 6500:3000
