#!/usr/bin/env bash

#load colors generated by pywal
source /home/lenan/.cache/wal/colors.sh

function run {
    if ! pgrep -f $1 ;
    then
        $@&
    fi   
}

# mouse gets set to second monitor by default for some reason...
# use this to move mouse to center of first monitor
xdotool mousemove 1280 720

# autostart programs
run unclutter --root
run /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
run picom --experimental-backends &
run numlockx on &
run xss-lock -- betterlockscreen -l blur &
#run caffeine -d &

sleep 1
#run blueman-applet &
#run keepassxc
#run variety
#run syncthingtray-qt6

## choose only one:
# redshift with systray
# run redshift-qt -l 41.722058311352065:2.9302747751915774 -t 6500:3000
# redshift without systray
run redshift -l 41.722058311352065:2.9302747751915774 -t 6500:3000 &
